### ISSUE TITLE
naza/playground/p3/p3.go 去掉 _ [56]byte 甚至性能还提升了

### ISSUE THREAD

**Issue by litterMY** [q191201771/naza#1]
go 1.16，去掉 _ [56]byte 甚至性能还提升了，是我理解的有问题吗

**Comment by q191201771** [comment]
CPU是啥，操作系统是啥，可以在网上找一些查看程序cache情况的工具看看。
这方面我也是新手，解答不了这个问题。
这个issue超时先关闭了，有问题可随时重新打开或创建新的issue，感谢。
